---
keepalived_enabled: true
conntrackd_enabled: true
strongswan_enabled: true
wireguard_enabled: true
frr_enabled: true

nftables_config:
  vars:
    wan_interface: eth0
    lan_interface: eth1
  tables:
    firewall:
      type: inet
      chains:
        input:
          hook: input
          policy: drop
        forward:
          hook: forward
          policy: drop
        output:
          hook: output
          policy: accept
        postrouting:
          type: nat
          hook: postrouting
          policy: accept
        prerouting:
          type: nat
          hook: prerouting
          policy: accept

nftables_networks:
  lan: [10.20.10.0/24]
  vpn: [10.100.0.0/27]

nftables_hosts:
  web01: 10.20.10.10
  mail01: 10.20.10.80

nftables_host_groups:
  public_web:
    hosts: [web01]
  mail_servers:
    hosts: [mail01]

nftables_services:
  web:
    protocols:
      tcp: [80, 443]
  mail:
    protocols:
      tcp: [25, 465, 587, 993]
  wireguard:
    protocols:
      udp: [51820]

nftables_rules:
  - chain: input
    protocol_raw: ip protocol ospf
    action: accept
  - chain: input
    source_interface: $lan_interface
    protocol_raw: ip protocol 112
    action: accept
  - chain: input
    source_interface: $lan_interface
    service: wireguard
    protocol: udp
    action: accept
  - chain: input
    source_interface: $lan_interface
    protocol: udp
    ports: [3780]
    action: accept
  - chain: input
    source_interface: $wan_interface
    service: wireguard
    protocol: udp
    action: accept
  - chain: forward
    source_interface: $lan_interface
    destination_interface: $wan_interface
    source_network: 10.20.10.0/24
    action: accept
  - chain: forward
    source_interface: $wan_interface
    destination_interface: $lan_interface
    destination_group: public_web
    service: web
    protocol: tcp
    action: accept
  - chain: forward
    source_interface: $wan_interface
    destination_interface: $lan_interface
    destination_group: mail_servers
    service: mail
    protocol: tcp
    action: accept
  - chain: forward
    source_interface: wg0
    destination_interface: $lan_interface
    source_network: 10.100.0.0/27
    action: accept
  - chain: prerouting
    source_interface: $wan_interface
    protocol: tcp
    ports: [80]
    destination_host: web01
    destination_port: 80
    action: dnat
  - chain: prerouting
    source_interface: $wan_interface
    protocol: tcp
    ports: [443]
    destination_host: web01
    destination_port: 443
    action: dnat
  - chain: prerouting
    source_interface: $wan_interface
    protocol: tcp
    service: mail
    destination_host: mail01
    action: dnat
  - chain: forward
    source_interface: $wan_interface
    destination_interface: wg0
    destination_network: 10.100.0.0/27
    ct_state: established,related
    action: accept
  - chain: forward
    source_interface: wg0
    destination_interface: $lan_interface
    destination_network: 10.20.10.0/24
    source_network: 10.100.0.0/27
    action: accept
  - chain: postrouting
    source_network: 10.20.10.0/24
    destination_interface: $wan_interface
    action: masquerade
  - chain: postrouting
    source_network: 10.100.0.0/27
    destination_interface: $wan_interface
    action: masquerade

keepalived_virtual_ipaddresses:
  - address: 10.10.10.2
    prefix: 24
    interface: eth0
  - address: 10.20.10.2
    prefix: 24
    interface: eth1
keepalived_password: ha
keepalived_ha_interface: eth1
keepalived_virtual_ip: 10.20.10.2
keepalived_virtual_ip_prefix: 24
conntrackd_multicast_address: 239.0.0.1
keepalived_virtual_ipaddress: >-
  {{ keepalived_virtual_ip }}/{{ keepalived_virtual_ip_prefix }}
  dev {{ keepalived_ha_interface }}

wireguard_vip_address: "10.10.10.2/24"
wireguard_key_mode: shared
wireguard_shared_private_key: ""
wireguard_interfaces:
  - name: wg0
    address: 10.100.0.1/27
    listen_port: 51820
    peers:
        # work
      - public_key: "Th4iePA5MCx60pmIkfTN0RFbuLBiaaD+s08+Bwm/enA="
        allowed_ips:
          - 10.100.0.2/32
        persistent_keepalive: 25
        # tel ana
      - public_key: "/lBnq6+qE5NXPWc2tY8B8xzsWBkVFI5VVD/1DzxWIRc="
        allowed_ips:
          - 10.100.0.3/32
        persistent_keepalive: 25
        # pc ana
      - public_key: "Ep7z6Ck8h5GOIDJzO8+mihmWjJJ3xe4T1rnW59JzVw4="
        allowed_ips:
          - 10.100.0.4/32
        persistent_keepalive: 25