nftables_config:
  vars:
  tables:
    firewall:
      type: inet
      chains:
        input:
          hook: input
          policy: drop
        forward:
          hook: forward
          policy: drop
        output:
          hook: output
          policy: accept
        postrouting:
          type: nat
          hook: postrouting
          policy: accept
        prerouting:
          type: nat
          hook: prerouting
          policy: accept
nftables_interfaces:
  wan: eth0
  lan: eth1

nftables_networks:
  lan:
  - 10.20.10.0/24
  vpn:
  - 10.100.0.0/27
nftables_hosts:
  web01: 10.20.10.10
  mail01: 10.20.10.80
nftables_host_groups:
  public_web:
    hosts:
    - web01
  mail_servers:
    hosts:
    - mail01
nftables_services:
  web:
    protocols:
      tcp:
      - 80
      - 443
  mail:
    protocols:
      tcp:
      - 25
      - 465
      - 587
      - 993
  wireguard:
    protocols:
      udp:
      - 51820
nftables_rules:
- chain: input
  protocol_raw: ip protocol ospf
  action: accept
- chain: input
  source_interface: lan
  protocol_raw: ip protocol 112
  action: accept
- chain: input
  source_interface: lan
  service: wireguard
  protocol: udp
  action: accept
- chain: input
  source_interface: lan
  protocol: udp
  ports:
  - 3780
  action: accept
- chain: input
  source_interface: wan
  service: wireguard
  protocol: udp
  action: accept
- chain: forward
  source_interface: lan
  destination_interface: wan
  source_network: 10.20.10.0/24
  action: accept
- chain: forward
  source_interface: wan
  destination_interface: lan
  destination_group: public_web
  service: web
  protocol: tcp
  action: accept
- chain: forward
  source_interface: wan
  destination_interface: lan
  destination_group: mail_servers
  service: mail
  protocol: tcp
  action: accept
- chain: forward
  source_interface: wg0
  destination_interface: lan
  source_network: 10.100.0.0/27
  action: accept
- chain: prerouting
  source_interface: wan
  protocol: tcp
  ports:
  - 80
  destination_host: web01
  destination_port: 80
  action: dnat
- chain: prerouting
  source_interface: wan
  protocol: tcp
  ports:
  - 443
  destination_host: web01
  destination_port: 443
  action: dnat
- chain: prerouting
  source_interface: wan
  protocol: tcp
  service: mail
  destination_host: mail01
  action: dnat
- chain: forward
  source_interface: wan
  destination_interface: wg0
  destination_network: 10.100.0.0/27
  ct_state: established,related
  action: accept
- chain: forward
  source_interface: wg0
  destination_interface: wan
  source_network: 10.100.0.0/27
  destination_network: 10.10.10.0/24
  action: accept
- chain: forward
  source_interface: wg0
  destination_interface: lan
  destination_network: 10.20.10.0/24
  source_network: 10.100.0.0/27
  action: accept
- chain: postrouting
  source_network: 10.20.10.0/24
  destination_interface: wan
  action: masquerade
- chain: postrouting
  source_network: 10.100.0.0/27
  destination_interface: wan
  action: masquerade
