---
nftables_enabled: true
nftables_config:
  vars: {}
  tables: {}
  path: /etc/nftables.conf
  service: nftables
nftables_services: {}
nftables_hosts: {}
nftables_host_groups: {}
nftables_networks: {}
nftables_rules: []
